package com.example.ui

object Localization {
    const val LANG_RU = "RU"
    const val LANG_UZ = "UZ"

    private val ruStrings = mapOf(
        "app_title" to "Electro Assistant",
        "app_sub" to "Интеллектуальный помощник электрика",
        "pin_title" to "ЗАЩИТНЫЙ ДОСТУП",
        "pin_enter" to "Введите 4-значный PIN-код",
        "pin_wrong" to "Неверный PIN-код!",
        "pin_create" to "Задайте новый 4-значный PIN-код",
        "pin_confirm" to "Запомните PIN-код для входов",
        "profile_title" to "ДАННЫЕ ИСПОЛНИТЕЛЯ",
        "profile_name" to "ФИО Исполнителя (Мастера)",
        "profile_grade" to "Разряд / Квалификация",
        "profile_save" to "СОХРАНИТЬ",
        "profile_saved" to "Данные сохранены!",
        "main_input_label" to "Текст для расчета (материалы и работы)",
        "main_input_hint" to "Пример:\nРозетки 3 штуки по 5000 сум\nКабель 10 метров по 12000 сум\nКоробка распределительная по 3500 сум",
        "main_btn_generate" to "СФОРМИРОВАТЬ И ОТПРАВИТЬ EXCEL",
        "main_empty_error" to "Сначала введите список материалов или приборов!",
        "main_parse_success" to "Файл с расчётом успешно сгенерирован!",
        "menu_home" to "Смета",
        "menu_reports" to "Архив",
        "menu_ai" to "ИИ Помощник",
        "reports_title" to "АРХИВ СМЕТ И ОТЧЁТОВ",
        "reports_empty" to "Список сохраненных отчётов пуст",
        "report_detail" to "ПРЕДПРОСМОТР РАСЧЁТА",
        "report_total" to "ИТОГО:",
        "report_date" to "Дата создания:",
        "report_usd_rate" to "Курс USD на тот момент:",
        "report_resend" to "ОТПРАВИТЬ ФАЙЛ EXCEL КЛИЕНТУ",
        "delete_confirm_title" to "Удаление отчёта",
        "delete_confirm_msg" to "Вы точно хотите удалить отчёт?!",
        "delete_yes" to "Да, удалить",
        "delete_no" to "Отмена",
        "ai_title" to "ИИ ПОМОЩНИК ЭЛЕКТРИКА",
        "ai_sub" to "Быстрые расчеты электрических цепей, подбор кабелей/автоматов по ПУЭ и ГОСТ, помощь в составлении смет.",
        "ai_hint" to "Напишите ваш запрос или вопрос. Например: 'Какое сечение кабеля нужно на розетки для духового шкафа?' или 'Приведи пример сметы на монтаж...' или 'Формула расчета тока сети...'",
        "ai_btn_ask" to "СПРОСИТЬ ПОМОЩНИКА",
        "ai_btn_loading" to "ОБРАБОТКА ЗАПРОСА И РАСЧЕТ...",
        "ai_safety_alert" to "РЕКОМЕНДАЦИЯ ПО ТЕХНИКЕ БЕЗОПАСНОСТИ!",
        "col_no" to "№",
        "col_name" to "Наименование оборудования/работ",
        "col_qty" to "Количество",
        "col_unit" to "Ед.",
        "col_price" to "Цена за ед. (сум)",
        "col_total" to "Итоговая сумма (сум)",
        "excel_total_row" to "ИТОГО",
        "excel_executor" to "ИСПОЛНИТЕЛЬ",
        "excel_grade" to "Квалификация",
        "rate_usd_title" to "Курс доллара к суму (Центробанк)",
        "total_usd" to "ИТОГО (доллары):",
        "photo_scanner_title" to "ФОТО-СКАНЕР СМЕТЫ",
        "photo_scanner_desc" to "Сделайте фото сметы/списка или выберите из галереи. Наш искусственный интеллект автоматически распознает рукописный или напечатанный на бумаге текст, найдет цены, количества и перенесет их в смету!",
        "photo_camera" to "КАМЕРА 📸",
        "photo_gallery" to "ГАЛЕРЕЯ 🖼️",
        "photo_processing" to "РАСПОЗНАВАНИЕ ТЕКСТА И РАСЧЁТ...",
        "photo_scan_status" to "Успешно распознано!",
        "photo_apply" to "ПРИМЕНИТЬ В СМЕТУ ✅",
        "photo_cancel" to "ОТМЕНА ❌",
        "bind_account_title" to "ПРИВЯЗКА GOOGLE-АККАУНТА 👤",
        "bind_account_desc" to "Привяжите ваш аккаунт Google, чтобы синхронизировать отчёты в защищённое облако Google Assistant Cloud и никогда их не потерять.",
        "bind_btn" to "ПРИВЯЗАТЬ GOOGLE АККАУНТ",
        "unbind_btn" to "ОТКЛЮЧИТЬ АККАУНТ",
        "account_linked" to "Google-аккаунт успешно привязан!",
        "cloud_sync_active" to "Облачная синхронизация отчётов активна",
        "excel_filename_title" to "Название Excel файла для отправки",
        "excel_filename_hint" to "Введите название (например, Замин)"
    )

    private val uzStrings = mapOf(
        "app_title" to "Electro Assistant",
        "app_sub" to "Elektrikning intellektual yordamchisi",
        "pin_title" to "XAVFSIZ KIRISh",
        "pin_enter" to "4 xonali PIN-kodni kiriting",
        "pin_wrong" to "PIN-kod noto'g'ri!",
        "pin_create" to "Yangi 4 xonali PIN-kod yarating",
        "pin_confirm" to "Kiritish uchun PIN-kodni eslab qoling",
        "profile_title" to "USTA MA'LUMOTLARI",
        "profile_name" to "Ustaning F.I.Sh.",
        "profile_grade" to "Malaka darajasi (Razryad)",
        "profile_save" to "SAQLASH",
        "profile_saved" to "Ma'lumotlar saqlandi!",
        "main_input_label" to "Hisoblash uchun matn (materiallar va ishlar)",
        "main_input_hint" to "Masalan:\nRozetkalar 3 ta dan 5000 so'm\nKabel 10 metr dan 12000 so'm\nTarqatish qutisi dan 3500 so'm",
        "main_btn_generate" to "EXCEL SHAKLLANTIRISH VA JUBORISH",
        "main_empty_error" to "Avval materiallar yoki uskunalar ro'yxatini kiriting!",
        "main_parse_success" to "Hisoblash fayli muvaffaqiyatli yaratildi!",
        "menu_home" to "Smeta",
        "menu_reports" to "Arxiv",
        "menu_ai" to "AI Yordamchi",
        "reports_title" to "HISOBOTLAR ARXIVI",
        "reports_empty" to "Saqlangan hisobotlar ro'yxati bo'sh",
        "report_detail" to "HISOBOT KO'RISH",
        "report_total" to "JAMI:",
        "report_date" to "Yaratilgan sana:",
        "report_usd_rate" to "O'sha vaqtdagi USD kursi:",
        "report_resend" to "EXCEL FAYLINI MIJOZGA JUBORISH",
        "delete_confirm_title" to "Hisobotni o'chirish",
        "delete_confirm_msg" to "Siz haqiqatan ham ushbu hisobotni o'chirmoqchimisiz?!",
        "delete_yes" to "Ha, o'chirish",
        "delete_no" to "Bekor qilish",
        "ai_title" to "ELEKTRIKNING AI YORDAMCHISI",
        "ai_sub" to "Elektr zanjirlarini hisoblash, PUE va GOST bo'yicha kabel/avtomat tanlash, smeta yozishda yordam.",
        "ai_hint" to "Murojaatingizni yozing. Masalan: 'Duxovka rozetkasi uchun qanday kabel kesimi kerak?' yoki 'Montaj smetasiga misol keltir...' yoki 'Tok kuchini hisoblash formulasi...'",
        "ai_btn_ask" to "YORDAMCHIDAN SO'RASH",
        "ai_btn_loading" to "JONLI TAHLIL VA HISOB-KITOB...",
        "ai_safety_alert" to "XAVFSIZLIK TEXNIKASI BO'YICHA TAVSIYA!",
        "col_no" to "T.r.",
        "col_name" to "Uskunalar / ishlar nomi",
        "col_qty" to "Soni",
        "col_unit" to "Birligi",
        "col_price" to "Dona narxi (so'm)",
        "col_total" to "Jami summa (so'm)",
        "excel_total_row" to "JAMI",
        "excel_executor" to "BAJARUVCHI",
        "excel_grade" to "Malaka darajasi",
        "rate_usd_title" to "USD kursi so'mga (Markaziy bank)",
        "total_usd" to "JAMI (USD):",
        "photo_scanner_title" to "SMETA FOTO-SKANERI",
        "photo_scanner_desc" to "Smeta rasmini oling yoki galereyadan tanlang. Sun'iy intellektimiz qo'lyozma yoki yozma matnni aniqlab, narx va sonlarni hisob-kitobga o'tkazadi!",
        "photo_camera" to "KAMERA 📸",
        "photo_gallery" to "GALEREYA 🖼️",
        "photo_processing" to "MATNNI TANISH VA HISOB-KITOB...",
        "photo_scan_status" to "Muvaffaqiyatli tanib olindi!",
        "photo_apply" to "SMETAGA QO'SHISH ✅",
        "photo_cancel" to "BEKOR QILISH ❌",
        "bind_account_title" to "GOOGLE HISOBINI ULASH 👤",
        "bind_account_desc" to "Hisobotlarni xavfsiz saqlash va Google Assistant Cloud bilan sinxronlash uchun Google hisobingizni ulang va ularni hech qachon yo'qotmang.",
        "bind_btn" to "GOOGLE HISOBINI ULASH",
        "unbind_btn" to "HISOBNI UZISH",
        "account_linked" to "Google hisobi muvaffaqiyatli ulandi!",
        "cloud_sync_active" to "Hisobotlar bulutli sinxronizatsiyasi faol",
        "excel_filename_title" to "Yuborish uchun Excel fayli nomi",
        "excel_filename_hint" to "Fayl nomini kiriting (masalan, Zamin)"
    )

    fun get(key: String, lang: String): String {
        val sMap = if (lang == LANG_UZ) uzStrings else ruStrings
        return sMap[key] ?: ruStrings[key] ?: key
    }
}
